apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.auth.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app:  {{ .Values.auth.name }}-svc
  type: ClusterIP
  sessionAffinty: {{ .Values.auth.service.sessionAffinity | quote }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10
  ports:
  - name:  {{ .Values.auth.service.port.name | quote }}
    port:  {{ .Values.auth.service.port.number }}
    targetPort:  {{ .Values.auth.service.port.targetPort }}