apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name:  {{ .Values.websock.name | quote }}
  labels:
    name:  {{ .Values.websock.name | quote }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  replicas: {{ .Values.websock.deployment.replicas | quote }}
  template:
    metadata:
      labels:
        name:  {{ .Values.websock.name | quote }}
    spec:
      containers:
      - image:  {{ .Values.websock.deployment.image.registry | default "sarthakjha" }}/{{ .Values.websock.deployment.image.name }}:{{ .Values.websock.deployment.image.tag }}
        name:  {{ .Values.websock.name | quote }}
        resources:
          requests:
            cpu: {{ .Values.websock.deployment.cpu | default "50Mi" }}
            memory: {{ .Values.websock.deployment.memory | default "10m" }}
        # livenessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        ports:
        - containerPort:  {{ .Values.websock.deployment.port | default 3000 }}
          name:  {{ .Values.websock.name | quote }}
      
        volumeMounts:
        - mountPath: /websock-config
          name: config
        env: 
          - name: POD_ID
            valueFrom: 
              fieldRef: 
                fieldPath: metadata.uid
          - name: JWT_SECRET
            valueFrom: 
              secretKeyRef:
                name: jwt-secret
                key: secret 
          - name: ACCESS_KEY_ID
            valueFrom: 
              secretKeyRef:
                name: aws-access-key-id
                key: secret
          - name: ACCESS_KEY_SECRET
            valueFrom: 
              secretKeyRef:
                name: aws-access-key-secret
                key: secret

      volumes:
        - name: config
          configMap: {{.Values.websock.name}}-cfmap
      restartPolicy: Always
      imagePullPolicy: Always
