apiVersion: v1
kind: Service
metadata:
  name:  "{{ .Values.websock.service.name }}"
spec:
  selector:
    app:  "{{ .Values.websock.service.selectorApp }}"
  type: ClusterIP
  sessionAffinty: "{{ .Values.websock.service.sessionAffinity }}"
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10
  ports:
  - name:  "{{ .Values.websock.service.port.name }}"
    port:  "{{ .Values.websock.service.port.number }}"
    targetPort:  "{{ .Values.websock.service.port.targetPort }}"