apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.websock.name }}-svc
spec:
  selector:
    app: {{ .Values.websock.name}}-svc
  type: ClusterIP
  sessionAffinty: {{ .Values.websock.service.sessionAffinity | quote}}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10
  ports:
  - name:  {{ .Values.websock.service.port.name | quote}}
    port:  {{ .Values.websock.service.port.number }}
    targetPort:  {{ .Values.websock.service.port.targetPort }}
